#pushing new code to buckate
steps:
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['SSH_KEY']
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "$$SSH_KEY" >> /root/.ssh/id_rsa
    chmod 400 /root/.ssh/id_rsa
    cp known_hosts.github /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Clone the repository
- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - --recurse-submodules
  - git@github.com:nithinbhandary/myrepo
  volumes:
  - name: 'ssh'
    path: /root/.ssh

availableSecrets:
  secretManager:
  - versionName: projects/sharp-avatar-368305/secrets/github/versions/latest
    env: 'SSH_KEY'


#copy from directory to bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '/home/nithinbhandry_gcp/dags', 'gs://us-west1-mucomp-d32b5ee5-bucket/dags/']


